apiVersion: apps/v1
kind: Deployment
metadata:
  name: flex-diary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flex-diary
  template:
    metadata:
      labels:
        app: flex-diary
    spec:
      containers:
        - name: flex-diary
          image: flexdiaryregistry.azurecr.io/flex-diary:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:example@mongodb:27017/your-database"
---
apiVersion: v1
kind: Service
metadata:
  name: flex-diary
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: flex-diary
