version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    container_name: api
    working_dir: /app
    ports:
      - "8080:8080"
      - "5005:5005"  # デバッグ用のポートを追加
    volumes:
      - ./api:/app  # ホットリロード用のボリュームマウント
      - /app/build  # コンテナ内でのみ使用するビルドディレクトリ
      - /app/.gradle  # コンテナ内の`.gradle`フォルダを独立させる

    environment:
      MONGO_CONNECTION_STRING: mongodb://root:example@mongodb:27017/admin
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mongodb

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      target: development
    container_name: ui
    working_dir: /app 
    ports:
      - "5173:5173" # viteサーバーのポート
      - "9229:9229" # デバッグポート
    volumes:
      - ./ui:/app  # ホットリロードを有効にするためにソースコードをマウント
      - /app/node_modules  # ホスト側のnode_modulesをコンテナから除外
    environment:
      - CHOKIDAR_USEPOLLING=true  # ホットリロードのための設定

volumes:
  mongodb-data:
