version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  app:
    image: amazoncorretto:21  # Dockerfileを使わずベースイメージを直接指定
    container_name: flex-diary-app
    working_dir: /app
    ports:
      - "8080:8080"
      - "5005:5005"  # デバッグ用のポートを追加
    volumes:
      - .:/app  # ホットリロード用のボリュームマウント
      - ./build/libs:/app/build/libs
    environment:
      MONGO_CONNECTION_STRING: mongodb://root:example@mongodb:27017/your-database
    depends_on:
      - mongodb
    entrypoint: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app/build/libs/app.jar"]


volumes:
  mongodb-data:
